# Generated by Django 4.0.2 on 2024-03-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
            ],
        ),
    ]
